### ISSUE TITLE
Flight animation

### ISSUE THREAD

**Issue by mishlaw** [mishlaw/AngryBirdsProject#1]
Анимация полета птицы. Столкновение с барьером пока нет.

**Comment by mishlaw** [comment]
Если пользователь не вводит никаких данных в первом окне, то расчеты производятся с заранее известными данными. Позже переделаю, чтобы была возможность читать их из файла. Чтобы увидеть анимацию, нужно нажать на изображение птички во втором окне.

**Comment by justjune** [comment]
Анимации не увидел.
